hello-world:
  replicaCount: 1
  image:
    repository: bcorpusjr/fortune-demo
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion. Use v2 for amd64
    tag: "arm-v0.2"

  service:
    type: ClusterIP
    port: 3000

namespace: dev
my_secret:
  foo: AgBcO3yzqLJTvPbIZay6PW1r0VNbTf7ebxae1HotbSAb3/wVb0LeHK2wzLKrjplH/qsSWzvQ6rKEPuND0rkW4eo1JmEgiDOOT4JUa3lgBxkev42i0+3IsJkcSGkw3SZcZLK68NxxqevU8IhUFD+0s2/lV81+UWdnoUTIJEGfS1XJjLhwjLUtLNpaLlk5bQ4qvjjj8XPdNaGUrHvQNBWkgUQ4fz8K3sCIAbSWOXCFdq6pRKL1UZ7vE5dLM/XSH59N/dJIYKdRLcPPITNsFrGWLCsc6h2hATt/JUjqmETZoVHuYUyGhosSFJZlyKHmDNEI4uBRS/c4B5a+uMX0SXkJ8/0SQbSM9mxa1fUFE8bg3OjYcD479YMmwkYLOTlQ0ArO/34HtSX7ruOxDv99Cqd8jJjLC0FuWBNXFO8qmE+vre74beHHL7oU1kTyfoOeiJSpy2bn+OlPlWJT0jJXkp6/Tjh+G3wj4FMr89Ulr2AR27L43jL5ClJfX26sg5Zjs/ToiZTLNTAsUrzrUcLG1XRZXe19WuiLAiiDdMoJlazXxwJKKGcr5DZ+XA2WyIuYR9rWSoaG5fCbtCslscgJO+ita7N1ZS2+oRL2gwSjr2Uts+L9J04ZjDYvoImvHNVqpqUIfHALLnIC1k3xkrgwGdq3EsQpKoK/ydBVqwnGw9OL7yaqOvblVfbd8YpuwnQR7xTBEVBk8Xw=

