hello-world:
  replicaCount: 1
  image:
    repository: bcorpusjr/fortune-demo
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  service:
    type: ClusterIP
    port: 3000
